### ISSUE TITLE
Book Club: Error Handling / Use Unchecked exceptions

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode#101]
Checked exceptions are when all of the exceptions a method could pass to a caller were a part of the type of the method. Meaning the code would not compile if the signature of the method doesn't match.

This was news to me. However, since C# doesn't have checked exceptions, it doesn't so much surprise me. 
The point of this section is to call out the breaking of the Open/Closed principle in checked exceptions,. 
If you throw a checked exception from a a method in your code and the catch is three levels above, you must declare that exception in the signature of each method between you and the catch. Which, breaks the encapsulation.

**Comment by jstevenson** [comment]
Since this doesn't apply in C#, is there anything to document? I would say that we could close this issue unless anyone thinks otherwise.

**Comment by dylanjustice** [comment]
> Since this doesn't apply in C#, is there anything to document? I would say that we could close this issue unless anyone thinks otherwise.

I'm fine with this. We document the Open/Closed principle elsewhere anyways.
