### ISSUE TITLE
Update "master" to "main" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ralphjmcintyre** [AndcultureCode/AndcultureCode#16]
![image](https://user-images.githubusercontent.com/8047934/93907034-e0015b00-fcca-11ea-9cfe-3a5b1690467f.png)

**Comment by brandongregoryscott** [comment]
It might be nice to have a note underneath saying that `main` _should_ be the default branch, but to double check with the specific repo to ensure it's been changed over, since not all of them have been yet,
