### ISSUE TITLE
Remove 'frontend' from .vscode/settings typescript path

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode#19]
```JSON
 "typescript.tsdk": "./frontend/node_modules/typescript/lib"
```

This configuration was originally based on one of our client projects, which contains a backend and frontend portion. Since this configuration is meant to be copied into new OSS repositories, most of which will _not_ contain a 'frontend' directory, I am proposing we strip that out to prevent confusion/incorrect TS versions being used.

**Comment by wintondeshong** [comment]
Yeah, I can get behind this. Especially being we have the boilerplate project now that should have this
