### ISSUE TITLE
Book Club: Document our use of "Clean Code: Make meaningful distinctions"

### ISSUE THREAD

**Issue by KevinBusch** [AndcultureCode/AndcultureCode#23]
Add documentation to clarify the content of the related section of the Clone Code book in this repository as it relates to AndcultureCode.  Add code examples when and where it makes the most sense in the languages we use.  All content should make use of or follow the patterns established in [`CODE_CONVENTIONS.MD`](https://github.com/AndcultureCode/AndcultureCode/blob/main/CODE-CONVENTIONS.md)

**Comment by Stefanie899** [comment]
Closing. PR #28 resolved this issue and has been merged in.
