### ISSUE TITLE
Pull request checklists

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode#7]
Discuss and implement Pull request checklist for across our various repositories. While there might be a few technology specific renditions, at its core there will general items that will likely span all projects.

**Comment by brandongregoryscott** [comment]
I'm thinking this would be a good start. Stripped out any specific technologies. Perhaps we could also add in links to our own documentation here, to help direct new contributors (a coding standards doc, test threshold specifications, etc)

- [ ] Destination branch has been merged before build and testing

- [ ] Code has been formatted and follows coding patterns

- [ ] Code builds cleanly (no warnings or errors)

- [ ] Changes have been manually tested

- [ ] Changes have the appropriate amount of automated test coverage

- [ ] All tests are passing

- [ ] Documentation updated (docs, comments, etc.)

**Comment by wintondeshong** [comment]
@brandongregoryscott thanks for putting thought to the checklists! Took that, added one or two and tried to make them a little shorter. What do you think?

- [ ] Related GitHub issue(s) linked in PR description
- [ ] Destination branch merged, built and tested with your changes
- [ ] Code formatted and follows best practices and patterns
- [ ] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [ ] Automated tests are passing
- [ ] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)
- [ ] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

**Comment by brandongregoryscott** [comment]
👍 That looks good to me. Good call specifying _addtional_ warnings/errors  😂

**Comment by wintondeshong** [comment]
Going to add this to each of the repositories
