### ISSUE TITLE
Book Club: Document our use of "Clean Code: Formatting - Horizontal Formatting - Indentation"

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode#71]
Add documentation to the clean code formatting document. Where applicable, add code examples to supplement your points in C# and TypeScript. All content should follow the patterns established in CODE_CONVENTIONS.MD

- Wrap blocks in curly braces when a single line ‘return’ with `if/else/etc...`.  There are exceptions in our languages (ie. C# expression bodies)
- If you indent more than two lines deep, strongly consider another function, short-circuiting, etc…
- Check for cross-reference between this location and functions

**Comment by KevinBusch** [comment]
Addressed with PR #77
