### ISSUE TITLE
Coding standards / Style guide

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode#8]
- [ ] Document auto formatting tools and rules sets per language
- [ ] Document team best practices (ie. region comments, alphabetical within regions, etc...)

**Comment by brandongregoryscott** [comment]
I had some time to sit down and document some of the things I look for in code reviews:

**Alphabetization**

- Properties, fields and members on interfaces, classes, and objects
- Methods by name within a region
    - This is less important for test methods/names within a region, so long as the region is alphabetically placed
- Constructor params
- Assignments within a constructor
- Named parameters in function calls (not necessarily on the signature itself)
- Error keys in localization files

Some common examples include:
- AclStrings
- DBSets in a Context, IContext
- IServiceCollectionExtensions DI registrations
- MappingProfile entries
- Props for rending a JSX Element/component

**Formatting**
For JavaScript, TypeScript and React, I prefer using Prettier. It takes the guesswork and debate out
of most formatting issues.

**Named parameters**
For the most part, I leave it up to preference. For methods that require 3 or more params, I would
err on the side of using them vs. not using them, to prevent any confusion or accidental mismatches
for signatures that take multiples of the same type.

For constructors, the benefit of using named parameters makes refactoring tests to accommodate a
new dependency easier.

**Comment by wintondeshong** [comment]
@brandongregoryscott thank you for taking the time to put this together! Believe you have covered all the bases of alphabetization. Only two points of refinement in my opinion would be around the regions...

- Properties, fields and members on interfaces, classes, and objects **within a given region**
- Regions themselves whenever a pre-established order does not exist
    - Pre-established: 
        - C# Class: private props, contructor, public methods, protected methods, private methods
        - TypeScript/JS: Constants, Interfaces, Types, Component, Exports
    - Unestablished:
        - Any language: Typically business-rule driven sub-regions

**Comment by brandongregoryscott** [comment]
Ah, yes! Good call. Forgot about regions. For C#, the standard `#region` and `#endregion` syntax is fine. For Typescript, I prefer the comment block/VS Code region hybrid:

```
// -----------------------------------------------------------------------------------------
// #region Example
// -----------------------------------------------------------------------------------------

// #endregion Example
```

In both cases, it is important to keep the `#endregion` with a name matching its starting `#region`

**Comment by wintondeshong** [comment]
I'm going to create a PR documenting our current stance around the ways we are using auto-formatting for typescript and c#. This can be a good jumping off point.

**Comment by brandongregoryscott** [comment]
Thanks @wintondeshong!
