### ISSUE TITLE
Add contributors across all repositories

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode#83]
[All Contributors](https://allcontributors.org/) has been added to the AndcultureCode organization and the app is available for use on all repositories. This approach is not entirely automatic, leaving the decision of who is on the list of contributors up to current maintainers (us). 

**Next Steps**
Using the list of repositories below, we need to systematically review each repos closed issues and pull requests. On a given contribution add a new comment of `@all-contributors please add @somegithubhandle for code, tests and etc`. Checkout the list of available [emoji keys](https://allcontributors.org/docs/en/emoji-key) as parameters following the `for` above.

Again, use your best judgement in adding contributors. Someone adding a single method XML documentation comment during hacktoberfest doesn't warrant contribution credit. On the other hand, folks providing code review feedback, but not actually contributing a single line of code should definitely get contribution for helping maintain the repository!

**Badges**
One item of note related to badges. Presently our badge list of floating inline with the title in the README. The bot's contribution requires the badge to be on a newline. Given this badge will likely be the third, fourth or even more, I feel we should just bump all badges onto a newline (right below the title)

See [AndcultureCode.CSharp.Core](https://github.com/AndcultureCode/AndcultureCode.CSharp.Core) to see an example

**Repository Checkout**
- [x] AndcultureCode.CSharp.Extensions
- [x] AndcultureCode.CSharp.Testing
- [x] AndcultureCode
- [x] AndcultureCode.CSharp.Core
- [x] AndcultureCode.CSharp.FactoryGirl
- [x] AndcultureCode.Cli
- [x] AndcultureCode.CSharp.Conductors
- [x] AndcultureCode.Scss.Grid
- [x] AndcultureCode.JavaScript.Website
- [x] AndcultureCode.CSharp.Web
- [x] AndcultureCode.JavaScript.Core
- [x] AndcultureCode.JavaScript.React
- [x] AndcultureCode.CSharp.Cli
- [x] AndcultureCode.DotnetReact.Boilerplate
- [x] AndcultureCode.JavaScript.Testing
- [x] AndcultureCode.JavaScript.React.Components
- [x] AndcultureCode.CSharp.Data
- [x] AndcultureCode.Cli.PluginExample
- [x] AndcultureCode.CSharp.Sitefinity.Testing
- [x] AndcultureCode.CSharp.Data.SqlServer
- [x] AndcultureCode.CSharp.Sitefinity.Core
- [x] AndcultureCode.JavaScript.Quill
- [x] AndcultureCode.CSharp.Data.PostgreSQL
- [x] AndcultureCode.CSharp.Sitefinity.Conductors

**Comment by brandongregoryscott** [comment]
Just found out the hard way, but for those going through it - it seems the bot does not resolve conflicts automatically, so I would add the first contributor, merge the PR first and then continue on adding contributors instead of bulk opening PRs

**Comment by wintondeshong** [comment]
> Just found out the hard way, but for those going through it - it seems the bot does not resolve conflicts automatically, so I would add the first contributor, merge the PR first and then continue on adding contributors 1 by 1 instead of bulk opening PRs

Thanks for the note @brandongregoryscott - I was "lucky" in my tests and just happened to do it one-by-one. I'm sure I would have run into this issue if you hadn't brought it up. 👍

**Comment by brandongregoryscott** [comment]
@wintondeshong I just wrapped up adding contributors for the last repo. However, I'm just now re-reading the comment in the issue about the badges - which is something I noticed seemed off too. I can do another sweep to make sure those look right.
